name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-telegram-bot
  cancel-in-progress: true  # Cancel any in-progress runs when a new push happens

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        run: |
          python bot.py
        env:
          TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
